# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teams.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 682)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(153, 215, 255, 255), stop:1 rgba(128, 145, 255, 255));")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(60, 50, 771, 251))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 31))
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 651, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(145, 102, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 90, 141, 41))
        self.pushButton_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(192, 255, 196);\n"
"border-radius:15px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(300, 170, 211, 21))
        self.progressBar.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(168, 110, 255);\n"
"")
        self.progressBar.setProperty("value", 34)
        self.progressBar.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 600, 191, 61))
        self.pushButton.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(144, 151, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 600, 191, 61))
        self.pushButton_2.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(94, 118, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 600, 191, 61))
        self.pushButton_3.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(94, 118, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 600, 191, 61))
        self.pushButton_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(144, 151, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(30, 40, 841, 301))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 111, 31))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 20, 531, 51))
        self.lineEdit_2.setStyleSheet("background-color: rgb(145, 102, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 130, 191, 41))
        self.pushButton_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(102, 255, 255);\n"
"border-radius:15px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(20, 30, 851, 331))
        self.frame_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(160, 20, 121, 31))
        self.label_7.setStyleSheet("color: rgb(80, 138, 59);")
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(110, 70, 121, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 100, 121, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(110, 130, 121, 31))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(512, 127, 121, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(179, 160, 255);\n"
"border-radius:15px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 40, 121, 31))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 95, 46);\n"
"border-radius:15px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 871, 521))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 801, 381))
        self.textBrowser.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(144, 151, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 440, 801, 51))
        self.lineEdit_3.setStyleSheet("background-color: rgb(192, 241, 255);\n"
"border-radius:15px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(10, 40, 861, 541))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lblTaskName = QtWidgets.QLabel(self.frame_5)
        self.lblTaskName.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.lblTaskName.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(118, 141, 206,0);\n"
"border-radius: 15px;")
        self.lblTaskName.setObjectName("lblTaskName")
        self.deadlineTask = QtWidgets.QLabel(self.frame_5)
        self.deadlineTask.setGeometry(QtCore.QRect(10, 90, 101, 41))
        self.deadlineTask.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(118, 141, 206,0);\n"
"border-radius: 15px;")
        self.deadlineTask.setObjectName("deadlineTask")
        self.lblDiff = QtWidgets.QLabel(self.frame_5)
        self.lblDiff.setGeometry(QtCore.QRect(10, 160, 101, 41))
        self.lblDiff.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(118, 141, 206,0);\n"
"border-radius: 15px;")
        self.lblDiff.setObjectName("lblDiff")
        self.resoursesLbl = QtWidgets.QLabel(self.frame_5)
        self.resoursesLbl.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.resoursesLbl.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(118, 141, 206,0);\n"
"border-radius: 15px;")
        self.resoursesLbl.setObjectName("resoursesLbl")
        self.lineInputTask = QtWidgets.QLineEdit(self.frame_5)
        self.lineInputTask.setGeometry(QtCore.QRect(160, 20, 501, 51))
        self.lineInputTask.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(160, 254, 255);\n"
"border-radius: 15px;")
        self.lineInputTask.setObjectName("lineInputTask")
        self.deadlineTime = QtWidgets.QDateTimeEdit(self.frame_5)
        self.deadlineTime.setGeometry(QtCore.QRect(160, 90, 251, 41))
        self.deadlineTime.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(160, 254, 255);\n"
"border-radius: 15px;")
        self.deadlineTime.setObjectName("deadlineTime")
        self.difficultSlider = QtWidgets.QSlider(self.frame_5)
        self.difficultSlider.setGeometry(QtCore.QRect(170, 170, 160, 22))
        self.difficultSlider.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(160, 254, 255);\n"
"border-radius: 15px;")
        self.difficultSlider.setOrientation(QtCore.Qt.Horizontal)
        self.difficultSlider.setObjectName("difficultSlider")
        self.resoursesList = QtWidgets.QTextBrowser(self.frame_5)
        self.resoursesList.setGeometry(QtCore.QRect(160, 230, 471, 231))
        self.resoursesList.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(249, 249, 163, 255), stop:1 rgba(255, 226, 192, 255));\n"
"border-radius:15px;")
        self.resoursesList.setObjectName("resoursesList")
        self.bthAdd = QtWidgets.QPushButton(self.frame_5)
        self.bthAdd.setGeometry(QtCore.QRect(340, 470, 141, 51))
        self.bthAdd.setStyleSheet("background-color: rgb(145, 188, 125);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;")
        self.bthAdd.setObjectName("bthAdd")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Teams plugin"))
        self.label.setText(_translate("Form", "Key:"))
        self.pushButton_5.setText(_translate("Form", "Connect"))
        self.pushButton.setText(_translate("Form", "Add team"))
        self.pushButton_2.setText(_translate("Form", "Connect"))
        self.pushButton_3.setText(_translate("Form", "Settings"))
        self.pushButton_4.setText(_translate("Form", "Teams"))
        self.label_3.setText(_translate("Form", "Team key:"))
        self.pushButton_6.setText(_translate("Form", "Search"))
        self.label_4.setText(_translate("Form", "Connection:"))
        self.label_5.setText(_translate("Form", "Teams:"))
        self.label_6.setText(_translate("Form", "Privacy:"))
        self.label_7.setText(_translate("Form", "Status"))
        self.checkBox.setText(_translate("Form", "Connect"))
        self.checkBox_2.setText(_translate("Form", "OpenSSL"))
        self.checkBox_3.setText(_translate("Form", "Chat"))
        self.pushButton_7.setText(_translate("Form", "Set"))
        self.pushButton_8.setText(_translate("Form", "Delete"))
        self.lblTaskName.setText(_translate("Form", "Task name"))
        self.deadlineTask.setText(_translate("Form", "Deadline"))
        self.lblDiff.setText(_translate("Form", "Difficulty"))
        self.resoursesLbl.setText(_translate("Form", "Resourses"))
        self.bthAdd.setText(_translate("Form", "Add task"))
